### ISSUE TITLE
Isolating environments into threads or processes

### ISSUE THREAD

**Issue by Mehooz** [danijar/dreamer#13]
Hi, I am trying to run your code with: python dreamer.py --logdir ./logdir/dmc_walker_walk/dreamer/ --task dmc_walker_walk --parallel process --envs 10
however, I got this error:
Traceback (most recent call last):
  File "dreamer.py", line 468, in <module>
    main(parser.parse_args())
  File "dreamer.py", line 434, in main
    tools.simulate(random_agent, train_envs, prefill / config.action_repeat)
  File "/home/zmh/mbmfec/dreamer/tools.py", line 125, in simulate
    obs, _, done = zip(*[p()[:3] for p in promises])
  File "/home/zmh/mbmfec/dreamer/tools.py", line 125, in <listcomp>
    obs, _, done = zip(*[p()[:3] for p in promises])
  File "/home/zmh/mbmfec/dreamer/wrappers.py", line 434, in _receive
    message, payload = self._conn.recv()
  File "/home/zmh/anaconda3/envs/dreamer/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/zmh/anaconda3/envs/dreamer/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/zmh/anaconda3/envs/dreamer/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

Even I wrote --envs=1, I got the same problem.
I am using python3.7 and tensorflow2.1. Thanks for spending some time on this!

**Comment by danijar** [comment]
Thanks for opening a ticket. The `--parallel` flag isn't supported at the moment. The code works well with `--parallel none` though, unless your environment uses global state and needs to be isolated into different processes. If you're interested, I'd be happy to accept a PR that gets fixes env isolation through threads or processes.
