### ISSUE TITLE
Missing Python dependencies

### ISSUE THREAD

**Issue by filangelos** [danijar/dreamer#14]
Comparing with the [original repo](https://github.com/google-research/dreamer), the following Python dependencies are missing:
* `gym`
* `Pillow`

**Comment by danijar** [comment]
I'm not quite sure I understand your comment. What makes you think that the dependencies should be the same for the two repositories?

**Comment by filangel** [comment]
let's forget about the other repo,
* `gym` is a dependency (https://github.com/danijar/dreamer/search?q=gym&unscoped_q=gym) and
* `Pillow` (or `scikit-image`) is a dependency too (https://github.com/danijar/dreamer/search?q=PIL&unscoped_q=PIL).

**Comment by danijar** [comment]
Okay, thanks. Note that Pillow is a dependency of matplotlib and gym is a dependency of dm_control. So if you install the packages listed in the readme, it should run. If that doesn't work for anybody, please let me know.

**Comment by filangel** [comment]
Cool!
I see your point for `Pillow` from the [`matplotlib/setup.py`](https://github.com/matplotlib/matplotlib/blob/master/setup.py#L257) but it doesn't seem to work (for me at least) :/

```
(base) ➜  ~ conda create -q -y -n test_dreamer python=3.6.9 && conda activate test_dreamer && pip install --upgrade pip matplotlib
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local/Caskroom/miniconda/base/envs/test_dreamer

  added / updated specs:
    - python=3.6.9


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/osx-64::certifi-2020.4.5.1-py36_0
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_0
  openssl            pkgs/main/osx-64::openssl-1.1.1f-h1de35cc_0
  pip                pkgs/main/osx-64::pip-20.0.2-py36_1
  python             pkgs/main/osx-64::python-3.6.9-h359304d_0
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-46.1.3-py36_0
  sqlite             pkgs/main/osx-64::sqlite-3.31.1-ha441bb4_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  wheel              pkgs/main/osx-64::wheel-0.34.2-py36_0
  xz                 pkgs/main/osx-64::xz-5.2.4-h1de35cc_4
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Preparing transaction: ...working... done
Verifying transaction: ...working...
done
Executing transaction: ...working... done
Requirement already up-to-date: pip in /usr/local/Caskroom/miniconda/base/envs/test_dreamer/lib/python3.6/site-packages (20.0.2)
Collecting matplotlib
  Downloading matplotlib-3.2.1-cp36-cp36m-macosx_10_9_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 70 kB/s
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting numpy>=1.11
  Using cached numpy-1.18.2-cp36-cp36m-macosx_10_9_x86_64.whl (15.2 MB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp36-cp36m-macosx_10_9_x86_64.whl (60 kB)
Collecting six>=1.5
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, python-dateutil, numpy, pyparsing, cycler, kiwisolver, matplotlib
Successfully installed cycler-0.10.0 kiwisolver-1.2.0 matplotlib-3.2.1 numpy-1.18.2 pyparsing-2.4.7 python-dateutil-2.8.1 six-1.14.0
(test_dreamer) ➜  ~ python -c "from PIL import Image"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'PIL'
(test_dreamer) ➜  ~ (base) ➜  ~ conda create -q -y -n test_dreamer python=3.6.9 && conda activate test_dreamer && pip install --upgrade pip matplotlib && pip list | grep Pillow
Collecting package metadata (current_repodata.json): ...working... python -c "from Pdone
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... IL import Idone
Solving environment: ...working... magdone
e"
## Package Plan ##

  environment location: /usr/local/Caskroom/miniconda/base/envs/test_dreamer

  added / updated specs:
    - python=3.6.9


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/osx-64::certifi-2020.4.5.1-py36_0
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_0
  openssl            pkgs/main/osx-64::openssl-1.1.1f-h1de35cc_0
  pip                pkgs/main/osx-64::pip-20.0.2-py36_1
  python             pkgs/main/osx-64::python-3.6.9-h359304d_0
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-46.1.3-py36_0
  sqlite             pkgs/main/osx-64::sqlite-3.31.1-ha441bb4_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  wheel              pkgs/main/osx-64::wheel-0.34.2-py36_0
  xz                 pkgs/main/osx-64::xz-5.2.4-h1de35cc_4
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Preparing transaction: ...working... done
Verifying transaction: ...working...
done
Executing transaction: ...working... done
Requirement already up-to-date: pip in /usr/local/Caskroom/miniconda/base/envs/test_dreamer/lib/python3.6/site-packages (20.0.2)
Collecting matplotlib
  Downloading matplotlib-3.2.1-cp36-cp36m-macosx_10_9_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 70 kB/s
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting numpy>=1.11
  Using cached numpy-1.18.2-cp36-cp36m-macosx_10_9_x86_64.whl (15.2 MB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp36-cp36m-macosx_10_9_x86_64.whl (60 kB)
Collecting six>=1.5
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, python-dateutil, numpy, pyparsing, cycler, kiwisolver, matplotlib
Successfully installed cycler-0.10.0 kiwisolver-1.2.0 matplotlib-3.2.1 numpy-1.18.2 pyparsing-2.4.7 python-dateutil-2.8.1 six-1.14.0
(test_dreamer) ➜  ~ python -c "from PIL import Image"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'PIL'
(test_dreamer) ➜  ~ pip list | grep Pillow
(test_dreamer) ➜  ~ pip list | grep PIL
(test_dreamer) ➜  ~ pip install -q --upgrade Pillow
(test_dreamer) ➜  ~ pip list | grep Pillow
Pillow          7.1.1
(test_dreamer) ➜  ~ python -c "from PIL import Image; print(Image)"
<module 'PIL.Image' from '/usr/local/Caskroom/miniconda/base/envs/test_dreamer/lib/python3.6/site-packages/PIL/Image.py'>
```

**Comment by danijar** [comment]
Okay, thanks. Good to know.
