### ISSUE TITLE
How to run Atari environments?

### ISSUE THREAD

**Issue by Jannkar** [danijar/dreamer#29]
I'm trying to run some Atari examples on Dreamer, but I cannot find correct parameters to do so without errors. When running the code for example with boxing environment, with the command:
`python dreamer.py --logdir ./logdir/atari/dreamer/1 --task atari_boxing` ,

I get an error:
```
...
Start evaluation.
Training for 100 steps.
[5000] expl_amount 0.0 / model_grad_norm inf / value_grad_norm 2.4 / actor_grad_norm 0.8 / prior_ent 35.6 / post_ent 32.7 / image_loss 11355.0 / reward_loss 0.9 / div 3.0 / model_loss 11355.0 / value_loss 1.1 / actor_loss -0.8 / action_ent -83.1
Traceback (most recent call last):
  File "dreamer.py", line 463, in <module>
    main(parser.parse_args())
  File "dreamer.py", line 442, in main
    tools.simulate(
  File "/home/jannkar/repositories/dreamer/tools.py", line 124, in simulate
    obs, _, done = zip(*[p()[:3] for p in promises])
  File "/home/jannkar/repositories/dreamer/tools.py", line 124, in <listcomp>
    obs, _, done = zip(*[p()[:3] for p in promises])
  File "/home/jannkar/repositories/dreamer/wrappers.py", line 350, in step
    obs, reward, done, info = self._env.step(action)
  File "/home/jannkar/repositories/dreamer/wrappers.py", line 162, in step
    obs, reward, done, info = self._env.step(action)
  File "/home/jannkar/repositories/dreamer/wrappers.py", line 211, in step
    obs, reward, done, info = self._env.step(action)
  File "/home/jannkar/repositories/dreamer/wrappers.py", line 320, in step
    raise ValueError(f'Invalid one-hot action:\n{action}')
ValueError: Invalid one-hot action:
[-0.9155  1.      1.      1.      0.1128 -1.     -1.      1.      0.9995
  0.9136 -1.      1.     -1.      0.9985 -1.      1.      0.9897 -1.    ]
```

I noticed that the code runs further when the `--action_dist onehot` is set and read that the `--pcont True` should be set as well. But the code still throws the same error, now just on line 447. So, what are the correct parameters that need to be set to run the Atari environments?

**Comment by IcarusWizard** [comment]
For Atari environment, you need to pass `--expl epsilon_greedy` to enable discrete exploration strategy.

**Comment by Jannkar** [comment]
Thanks a lot for your answer! Running now smoothly.
