### ISSUE TITLE
Invalid one-hot action with Google Research football environment

### ISSUE THREAD

**Issue by jgonik** [danijar/dreamer#39]
Hi! I'm trying to train Dreamer on [the Google Research football environment](https://github.com/google-research/football). When training, I get the following error:

```
Traceback (most recent call last):
  File "dreamer.py", line 471, in <module>
    main(parser.parse_args())
  File "dreamer.py", line 451, in main
    functools.partial(agent, training=False), test_envs, episodes=1)
  File "/home/gridsan/jgonik/my-dreamer/tools.py", line 124, in simulate
    obs, _, done = zip(*[p()[:3] for p in promises])
  File "/home/gridsan/jgonik/my-dreamer/tools.py", line 124, in <listcomp>
    obs, _, done = zip(*[p()[:3] for p in promises])
  File "/home/gridsan/jgonik/my-dreamer/wrappers.py", line 379, in step
    obs, reward, done, info = self._env.step(action)
  File "/home/gridsan/jgonik/my-dreamer/wrappers.py", line 191, in step
    obs, reward, done, info = self._env.step(action)
  File "/home/gridsan/jgonik/my-dreamer/wrappers.py", line 240, in step
    obs, reward, done, info = self._env.step(action)
  File "/home/gridsan/jgonik/my-dreamer/wrappers.py", line 349, in step
    raise ValueError(f'Invalid one-hot action:\n{action}')
ValueError: Invalid one-hot action:
[ 1.      0.9995 -0.9995 -0.9775 -0.99   -1.      1.     -0.999   1.
  0.9995  0.999  -0.999   0.9995 -0.9995 -1.      0.9985 -1.     -1.
  1.    ]
```

I saw that people have previously encountered this issue with the Atari environment (#29), and the solution there was to use the `epsilon_greedy` exploration strategy. However, I get this error no matter which exploration strategy I use. Any help would be greatly appreciated!

**Comment by jgonik** [comment]
Resolved; the issue was actually with some other model parameters :)
